import axios from 'axios'

const HOST_URL = 'https://rn-expense-tracker-cbc78-default-rtdb.firebaseio.com'

export async function hostGetExpenses() {
    // fetch
    const response = await axios.get( HOST_URL + '/expenses.json')
    const expenses = []

    for (const key in response.data) {
        const expenseObj = {
            id: key,
            date: new Date(response.data[key].date),
            amount: response.data[key].amount,
            description: response.data[key].description,
        }
        expenses.push(expenseObj)
    }
    return expenses
}


export async function hostPostExpense(expenseData) {
    // add
    const response = await axios.post( 
        HOST_URL + '/expenses.json', 
        expenseData
    )
    const id = response.data.name // this is the auto created id generated by firebase
    console.log('Added ID: ', id)
    return id
}


export async function hostPutExpense( id, expenseData ) {
    // update
    return await axios.put( HOST_URL + `/expenses/${id}.json`, expenseData )
}


export async function hostDeleteExpense(id) {
    // delete
    return await axios.delete( HOST_URL + `/expenses/${id}.json` )
}